# See https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html

namespace: guidograzioli
name: kubevirt
version: 0.1.0
readme: README.md
authors:
  - Felix Matouschek (github.com/0xFelix)
dependencies:
    kubernetes.core: '>=2.0.0'
description: KubeVirt Collection for Ansible
license_file: LICENSE
tags:
# tags so people can search for collections https://galaxy.ansible.com/search
# tags are all lower-case, no spaces, no dashes.
  - api
  - k8s
  - kubernetes
  - kubevirt
  - virtualization
  - cloud
  - infrastructure
repository: https://github.com/0xFelix/kubernetes.kubevirt
documentation: https://github.com/0xFelix/kubernetes.kubevirt/tree/main/docs
homepage: https://github.com/0xFelix/kubernetes.kubevirt
issues: https://github.com/0xFelix/kubernetes.kubevirt/issues
build_ignore:
# https://docs.ansible.com/ansible/devel/dev_guide/developing_collections_distributing.html#ignoring-files-and-folders
  - .gitignore
  - changelogs/.plugin-cache.yaml
