apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: fedora
spec:
  runStrategy: Always
  template:
    metadata:
      labels:
        app: test
    spec:
      domain:
        devices:
          disks:
          - disk:
              bus: virtio
            name: containerdisk
          - disk:
              bus: virtio
            name: cloudinit
          rng: {}
          interfaces:
          - name: default
            masquerade: {}
          - name: bridge-network
            bridge: {}
        features:
          acpi: {}
          smm:
            enabled: true
        firmware:
          bootloader:
            efi:
              secureBoot: true
        resources:
          requests:
            memory: 1Gi
      networks:
      - name: default
        pod: {}
      - name: bridge-network
        multus:
          networkName: kindexgw
      terminationGracePeriodSeconds: 180
      volumes:
      - containerDisk:
          image: quay.io/containerdisks/fedora:latest
        name: containerdisk
      - cloudInitNoCloud:
          userData: |-
            #cloud-config
            # The default username is: fedora
            ssh_authorized_keys:
              - ssh-ed25519 AAAA...
        name: cloudinit
